name: Image Update

on:
  push:
    branches:
      - main
      - dependabot/**
    paths:
      - .github/workflows/image-update.yml
      - Dockerfile
      - values.yaml
      - Chart.yaml
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest image
        id: latest
        run: |
          IMAGE=$(cat Dockerfile | grep FROM | cut -f2 -d' ')
          
          echo "::set-output name=repository::$(cut -f1 -d':' <<< $IMAGE)"
          echo "::set-output name=tag::$(cut -f2 -d':' <<< $IMAGE)"

      - name: Get current image
        id: current
        run: |
          echo "::set-output name=repository::$(yq e '.image.repository' values.yaml)"
          echo "::set-output name=tag::$(yq e '.image.tag' values.yaml)"

      - name: Update
        run: |
          yq -i '.image.repository = strenv(REPOSITORY)' values.yaml
          yq -i '.image.tag = strenv(TAG)' values.yaml
          yq -i '.appVersion = strenv(TAG)' Chart.yaml
        env:
          REPOSITORY: ${{ steps.latest.outputs.repository }}
          TAG: ${{ steps.latest.outputs.tag }}

      - name: Create Pull Request
        if: ${{ github.ref_protected }}
        uses: peter-evans/create-pull-request@v5
        with:
          title: "fix(chart): bump ${{ steps.latest.outputs.repository }} from ${{ steps.current.outputs.tag }} to ${{ steps.latest.outputs.tag }}"
          commit-message: "fix(chart): bump ${{ steps.latest.outputs.repository }} from ${{ steps.current.outputs.tag }} to ${{ steps.latest.outputs.tag }}"
          body: "Update Helm Chart from dummy Dockerfile"
          branch: image-update--${{ github.ref_name }}
          delete-branch: true
          labels: bot,dependencies

      - name: Commit
        if: ${{ !github.ref_protected }}
        run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          
          git add Chart.yaml values.yaml
          git commit -m 'fix(chart): bump ${{ steps.latest.outputs.repository }} from ${{ steps.current.outputs.tag }} to ${{ steps.latest.outputs.tag }}'
          git push
